### ISSUE TITLE
How does the scheduler start scheduling?

### ISSUE THREAD

**Issue by arianf** [keylimetoolbox/resque-kubernetes#27]
I'm curious how this gem runs jobs from the scheduler? I don't see anything in the README.md

**Comment by jeremywadsack** [comment]
Hi @arianf. `resque-kubernetes` doesn't do anything special for the `resque-scheduler` extension. I don't see any reason why you couldn't run it though. 

You would need to [run the `resque-scheduler` server](https://github.com/resque/resque-scheduler#standalone-executable) as a separate pod/deployment in your Kubernetes cluster. `resque-scheduler` sends "due" jobs to their appropriate queue. When it calls `enqueue` on the job, it will fire the hook to spin up new Kubernetes Job pods (if needed) and autoscale just as with normal jobs.

Let me know if this works for you. If so, happy to accept a PR for a README update including a mention of it.

**Comment by arianf** [comment]
Hmm thanks for explaining that!
