### ISSUE TITLE
How to start workers in Docker passenger container?

### ISSUE THREAD

**Issue by bhushangahire** [keylimetoolbox/resque-kubernetes#29]
I am trying to find a way to start the worker queue when the container runs but am not able to find a way to do it. 
Any pointers?

**Comment by jeremywadsack** [comment]
Hi @bhushangahire Sorry for the very late response — I'm not sure I understand your question. 

You can set up a Dockerfile with that runs `bin/rails environment resque:work` to start the worker as [described in the README](https://github.com/keylimetoolbox/resque-kubernetes#workers-for-both).
